spring:
  application:
    name: medicos-service
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:medicosdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:medicos_test
server:
  port: 9082

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:file:./data/medicosdb
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
server:
  port: 8082
