spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: pacientes-service
          uri: lb://PACIENTES-SERVICE
          predicates:
            - Path=/api/pacientes/**
        - id: medicos-service-medicos
          uri: lb://MEDICOS-SERVICE
          predicates:
            - Path=/api/medicos/**
        - id: medicos-service-especialidades
          uri: lb://MEDICOS-SERVICE
          predicates:
            - Path=/api/especialidades/**
        - id: medicos-service-horarios
          uri: lb://MEDICOS-SERVICE
          predicates:
            - Path=/api/horarios/**
        - id: medicos-service-consultorios
          uri: lb://MEDICOS-SERVICE
          predicates:
            - Path=/api/consultorios/**
        - id: citas-service-citas
          uri: lb://CITAS-SERVICE
          predicates:
            - Path=/api/citas/**
        - id: citas-service-estados
          uri: lb://CITAS-SERVICE
          predicates:
            - Path=/api/estados-cita/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 9080

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 80
